#!/usr/bin/env python

import subprocess
import logging

logging.basicConfig(filename='/home/git/gitlab/log/gl_backup.log',
                    format='%(asctime)s [%(levelname)s] %(message)s',
                    datefmt='%Y-%m-%dT%H:%M:%S',
                    level=logging.INFO)
logging.info('*' * 52)
logging.info('Starting gitlab backup')
pr = subprocess.Popen(['bundle', 'exec', 'rake', 'gitlab:backup:create', 'RAILS_ENV=production'],
                      cwd='/home/git/gitlab',
                      stdout=subprocess.PIPE,
                      stderr=subprocess.STDOUT,
                      shell=False)
(out,err) = pr.communicate()
logging.info("bundle exec rake gitlab:backup:create RAILS_ENV=production\n"+out)
logging.info('Ending gitlab backup')
